### ISSUE TITLE
Required package CoinUtils not available.

### ISSUE THREAD

**Issue by daemontus** [dreal/homebrew-dreal#1]
Hi, on vanilla macOS, the installation fails with the following configure error:

```
checking for COIN-OR package CoinUtils... skipped check via pkg-config, redirect to fallback
checking for COIN-OR package CoinUtils (fallback)... no, dependency coinutils not available
configure: error: Required package CoinUtils not available.
```

This can be fixed by setting the `PKG_CONFIG` and `PKG_CONFIG_PATH`, as suggested [here](https://github.com/coin-or-tools/homebrew-coinor/issues/42). But it is still a little annoying :)

**Comment by soonho-tri** [comment]
Hi @daemontus , thanks for the report. Yes, this is a known upstream issue and I'm aware of it. There is an open PR, https://github.com/coin-or-tools/homebrew-coinor/pull/43, which is not processed yet.
